default: &default
  adapter: jdbc

jruby:
  development:
    <<: *default
    database: sqlite:db/development.sqlite3

  test:
    <<: *default
    database: sqlite:db/test.sqlite3

  production:
    <<: *default
    database: jtds:sqlserver://<%= ENV['PIMS_DB_SERVER'] %>/<%= ENV['PIMS_DATABASE'] %>;user=<%= ENV['PIMS_USER'] %>;password=<%= ENV['PIMS_PASSWORD'] %>

ruby:
  default: &default_ruby
    adapter: tinytds

  development:
    <<: *default_ruby
    adapter: sqlite
    database: db/development.sqlite3   # if memory, set it to empty

  test:
    <<: *default_ruby
    adapter: sqlite
    database: db/test.sqlite3

  production:
    <<: *default_ruby
    user: <%= ENV['PIMS_USER'] %>
    password: <%= ENV['PIMS_PASSWORD'] %>
    database: <%= ENV['PIMS_DATABASE'] %>
    dataserver: <%= ENV['PIMS_DB_SERVER'] %>